### PR TITLE
Removed Empty Space in Navbar

### LINKED ISSUE #315: Empty Space in Navbar
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

There is unpleasant empty space in the navbar, which should be removed by either reducing the size of the logo or increasing the size of the text/dropdown menu button.

**Expected Behaviour**

The navbar should be adjusted to reduce the amount of empty space

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Ryan10145**
#### Checklist

- [X] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [X] There is a corresponding issue for this pull request.
- [X] My branch is up-to-date with the Upstream `master` branch.
- [X] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:

There is unplesant white space in the navbar

screen shot 2018-10-24 at 11 49 57 am

#### Changes proposed in this pull request:

Changes the navbar size to make it larger and reduce whitespace.

screen shot 2018-10-24 at 11 49 07 am

Fixes #315

### CODE REVIEW

**Comment by rpotter12** [comment]
@Ryan10145 for every frontend changes please paste the deployed heroku link. This will help us to review your PR more perfectly. Thank you

**Comment by sarnava1** [comment]
@Ryan10145 yes you should submit heroku link for better and faster review. I some cases even screenshots work. And when your are filing a PR you have checked all the tickboxes. So you need to specify whoch tests you have carried out. @meets2tarun can help you more on this issue. Otherwise good going and keep it up.

**Comment by sarnava1** [comment]
@Ryan10145 when you are doing frontend changes try to give the heights or paddings in % or vh vw rather than px since we need to make this web app responsive across all screens. @tabesin you can merge this as of now.

**Comment by rpotter12** [comment]
@Ryan10145 always open an issue before creating any PR. Thank you :)

**Pull request merged**
