### PR TITLE
Optimise build.html in /output route for mobiles

### LINKED ISSUE #301: Optimize build.html page for mobiles that's displayed in /output route
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
image
As you can see, everything's overlapping.

**Expected Behaviour**
Would be really nice if we optimize it for phones.

**Other information:**

Minor mods to the html and css files

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by rahulkumaran**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This PR makes sure that build html looks better on mobile phones. Had to close the previous pr

#### Changes proposed in this pull request:
- added email.css link to layout.html
- added width for images in build.html
- add margin in email.css

Fixes #301 
Had to close my previous PR #304 as there were some issues with it.
The same changes can be viewed on https://rahulkumaran-meilix.herokuapp.com

show

### CODE REVIEW

**Comment by rahulkumaran** [comment]
So that I can add if I put some <br> but I'm not able to edit the css for the margin. In the previous PR I added the break statements but later removed it on request. So yeah, if the spacing is needed then I'll have to add the break statements. @tabesin @meets2tarun

**Comment by sarnava1** [comment]
@rahulkumaran why can't we edit the css for the margin?

**Comment by rahulkumaran** [comment]
Idk! Tried it out but wasn't happening! The br thing was the only one that worked

**Comment by sarnava1** [comment]
@rahulkumaran ohh!!! Okay let's see what the others are saying @mariobehling @tabesin @meets2tarun

**Comment by pranav1698** [comment]
LGTM, if you would have posted a heroku link then we could also try to see if masrgin works or not

**Comment by rahulkumaran** [comment]
@pranav1698, I've posted the heroku link in the PR description. Have a look haha

**Comment by pranav1698** [comment]
Sorry for not checking it clearly @rahulkumaran

**Comment by rahulkumaran** [comment]
@pranav1698 don't be! It's totally cool, happens sometimes.

**Comment by pranav1698** [comment]
I have checked it adding margin-bottom to the css and putting a positive value in it will solve this;
screenshot from 2018-10-31 01-09-42
You can give a unique  id to this container tag to avoid inline-css

**Comment by rahulkumaran** [comment]
Exactly I tried that. But it's not responding to the changes. It works with inline but in my previous PR I was suggested not to use inline so I tried shifting it an ID and gave the CSS stuff in the email.css file but to no effect. @pranav1698

**Comment by rahulkumaran** [comment]
@pranav1698, works well now. Tried it in the wrong place previously. Thanks for the help !

**Comment by pranav1698** [comment]
@rahulkumaran feels great to be of help,
Post the screenshot of the present build

**Comment by rahulkumaran** [comment]
image
@pranav1698 @sarnava1 @tabesin @mariobehling @meets2tarun

**Comment by pranav1698** [comment]
LGTM :+1:

**Comment by rpotter12** [comment]
Your heroku link is not working properly.
After clicking on build button an error is coming "unexpected Travis tag". Please solve this:)

**Comment by rahulkumaran** [comment]
It works perfectly for me and I guess the others also have already used the link! @rpotter12
Not sure why you're getting that error! Will check though

**Comment by rpotter12** [comment]
@meets2tarun please check the heroku deployment link, is that working for you also??

**Comment by rahulkumaran** [comment]
@tabesin @meets2tarun @mariobehling, could please review this? Thanks! 😁

**Pull request merged**
