### PR TITLE
This adds option for choice of processor using the 64bit support toggle - (Solves- #409)

### LINKED ISSUE #409: The 32bit or 64bit support toggle does not provide any information submission
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Expected Behaviour**
The 32bit or 64bit toggle does not provide any information on form post.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by pranav1698**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This adds an option for choice of processor(64bit or 32bit) using the bit support toggle 
Now, we can add an option on the build scripts in the main repo for 32bit or 64bit support

#### Changes proposed in this pull request:

- Adding a name,value pair for the 64bit support toggle 
- Storing the value of the toggle in a variable named processor
- The processor variable is then sent to the build server

Fixes #409

### CODE REVIEW

**Comment by pranav1698** [comment]
Hosted site: https://shielded-coast-16793.herokuapp.com/

**Comment by pranav1698** [comment]
@tabesin we can ignore the codacy error, it will not effect the working of the webapp and I think it is a good practise to having spaces between defining the variables, 
Also, I am taking that the default version is  32bit for this pr, whereas we are using the 64bit as default for the meilix main repo, so I think 64bit should be considered as default

**Comment by tabesin** [comment]
yes 64 bit as default. Also for the normal build run without webapp trigger.

**Comment by pranav1698** [comment]
@tabesin, That is been taken care in the meilix repo opened a pr for that: https://github.com/fossasia/meilix/pull/422
I will update for 64bit as default

**Comment by pranav1698** [comment]
@tabesin please review now

**Comment by pranav1698** [comment]
@rpotter12 I have rebased my heroku master branch as I have started working on other issue
Please merge it the functionality remains the same for the generator

**Comment by pranav1698** [comment]
Conflicts resolved @tabesin please merge

**Pull request merged**
