### PR TITLE
Send generator-package array as json-array to the build server - (Solves- #397) 

### LINKED ISSUE #397: Sending the generator package variables to the build server
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Expected Behaviour**
After #396 is merged we need a way to send the generator packages array from the webapp to the build server

**Would you like to work on the issue?**
Yes

### LINKED ISSUE #398: Replacing the way to send the wallpaper, logo, and zipfiles from the webapp to build server
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Expected Behaviour**
In the current build, wallpaper in stored in the wallpapers folder in the server and previously this was accessed during the build by accessing `https://meilix-generator.herokuapp.com/`. This can cause same wallpaper for two different users which have build the ISO using the generator. 

**Would you like to work on the issue?**
Open

### PR DESCRIPTION
**Pull request by pranav1698**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This sends the generator-package array from the webapp to the build server sending it as a json array
This array can be further used in the build server for installing packages

#### Changes proposed in this pull request:

- Dumping the package array into a json array
- Sending the json array to the build server with the trigger request
-

Fixes #397

### CODE REVIEW

**Comment by pranav1698** [comment]
Hosted site: https://boiling-thicket-10511.herokuapp.com/

**Comment by tabesin** [comment]
The terminology packages is equally obscure as features though. It should be made more transparent to a person unfamiliar with the code what is happening there. 

 ok,go fwd

**Comment by pranav1698** [comment]
Should we replace it with softwares??

**Comment by tabesin** [comment]
I called it receipe previously.

**Comment by pranav1698** [comment]
Ok, going with recipes

**Comment by pranav1698** [comment]
@tabesin please review now

**Comment by xeon-zolt** [comment]
LGTM

**Comment by xeon-zolt** [comment]
> I called it receipe previously.

recipe word looks confusing to me

**Comment by tabesin** [comment]
ingredients?

**Pull request merged**
