### PR TITLE
fixes #257

### LINKED ISSUE #257: Add yaydoc, susi.ai for magic mirror and Badgeyay in FOSSASIA projects
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
We should include yaydoc, susi.ai and badgeyay in FOSSASIA projects
 **Would you like to work on the issue?**
YES.

### PR DESCRIPTION
**Pull request by sarnava1**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Badgeyay, SUSI.AI for magic mirror and yaydoc added to FOSSASIA projects.

Fixes #257

### CODE REVIEW

**Comment by sarnava1** [comment]
@tabesin please review and merge this now.

**Comment by tabesin** [comment]
Needs to rebased. Does not apply cleanly.

**Comment by sarnava1** [comment]
@tabesin I did not get you!!

**Comment by tabesin** [comment]
This has merge conflicts and undoes recent changes.

**Comment by sarnava1** [comment]
@tabesin I am closing this and filing a new PR soon.

**Pull request closed without merging**
