### PR TITLE
Fixed Contrast

### LINKED ISSUE #387: Improve contrast of new theme
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

The new theme lacks contrasts, which makes it difficult to follow on some devices.

**Expected Behaviour**

**Steps to reproduce it**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixed contrast of the text, header, and footer a little bit. 

Fixes #387 

**Screenshots**
screenshot from 2019-01-21 17-16-30

screenshot from 2019-01-21 17-16-40

### CODE REVIEW

**Comment by rajvaibhavdubey** [comment]
@tabesin Is this okay?

**Comment by niteshkumarniranjan** [comment]
@rajvaibhavdubey I agree on increasing the contrast but the grey you choose is a wrong grey. You have changed the hue.

**Comment by niteshkumarniranjan** [comment]
Okay! My bad the previous UI already had enough contrast I just didn't compared it with the previous version.

**Comment by niteshkumarniranjan** [comment]
@pranav1698 I think I should create a style guide to have the consistency across the PRs

**Pull request merged**
