### PR TITLE
fix navbar

### LINKED ISSUE #355: The Dropdown menu and the menu button is not responsive for mobiles
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The drop down menu and the menu button is not responsive for mobiles
screenshot_20181203_231018
screenshot_20181203_231036
- The icons inside the drop down get out of the menu on mobiles
screenshot_20181203_231047
  
 - The menu button is not aligned with the title and it does not look good 

**Expected Behaviour**
The web-app should be made responsive for mobiles, the grey container is also not coming inside the nav-bar as expected

**Steps to reproduce it**

- Open the site on mobiles

Your operating system
``` Ubuntu 18.04```

**Would you like to work on the issue?**
No, This can be assigned to GCI participants

### PR DESCRIPTION
**Pull request by pythongiant**
fix navbar

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fix the navbar

#### Changes proposed in this pull request:
Fix Navbar for mobile devices
screenshot_3

-https://gentle-beyond-35732.herokuapp.com/
-
-

Fixes #355

### CODE REVIEW

**Comment by pythongiant** [comment]
@pranav1698 check it out now?

**Comment by pythongiant** [comment]
@pranav1698 i dont follow

**Comment by pythongiant** [comment]
LGTM on my screen

**Comment by pranav1698** [comment]
have you checked it on your phone 
Open susper for comparison you will see the difference it may here because of white background

**Comment by pythongiant** [comment]
ummm @pranav1698  that's due to the fact that there are more icons in this dropdown

**Comment by pranav1698** [comment]
So you can increase the size of the drop-down container to fit in with the total number of the items,

**Comment by pythongiant** [comment]
@pranav1698 i am gonna add a scrolbar if that's fine?

**Comment by pythongiant** [comment]
nevermind closing this PR

**Pull request closed without merging**
