### PR TITLE
adjusting the page appearance

### PR DESCRIPTION
**Pull request by rpotter12**
#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] There is a corresponding issue for this pull request.
- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- Changes in code of 404.html for better appearance.
- improving appearance of index.html

Fixes #

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@rpotter12 Thanks for your contribution, there are merge conflicts because the index file changed, too. Would you like to have a look and resolve them?
If you need help with git in doing so, let us know! :)

**Comment by meets2tarun** [comment]
hi, @rpotter12 Thanks a lot. 
Don't hesitate to ask for any help you need.

**Comment by rpotter12** [comment]
@niccokunzmann I am new in contributing to an organization. 

I want to ask, "What about the change of 404.html ?"

I meant to say that I have made changes in 404.html also, so I have to create a new pull request or you can change code with this pull request.

**Comment by meets2tarun** [comment]
@rpotter12 , Welcome to the organisation.
> I want to ask, "What about the change of 404.html ?"

404.html file get changed in the past therefore there is no issues with that.
You just try the resolved conflicts present in index.html. You can try doing that or you if face any issue then reach out to us here or on http://gitter.im/fossasia/meilix

**Comment by meets2tarun** [comment]
@rpotter12 After that, please put a screenshot of the changes that you made in the PR.

Thanks

**Pull request closed without merging**
