### PR TITLE
Added option for uploading a vector logo-(Solves issue#107)

### LINKED ISSUE #107: Create Upload for vector logo upload
create upload vector logo similar to wallpaper for the OS branding to be used for Plymouth and start menu.

### PR DESCRIPTION
**Pull request by pranav1698**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This adds a option(similar to wallpaper) to upload a vector logo for the desktop to the user

#### Changes proposed in this pull request:

-Adding an upload logo button similar upload wallpaper option
-
-

Fixes #107

### CODE REVIEW

**Comment by pranav1698** [comment]
GIF for present changes:
meilix

**Comment by xeon-zolt** [comment]
@pranav1698 Flask code also need to be edited to get the image

**Comment by xeon-zolt** [comment]
we need to store logo like we did for wallpaper then we need to tweak meilix for using that logo in for example plymouth

**Comment by tabesin** [comment]
What does logo mean other than wallpaper?

**Comment by tabesin** [comment]
We should not have plymouth custom teaming for now as it is quite complicated.

**Comment by pranav1698** [comment]
@tabesin what do I need to do for now for the pr

**Comment by meets2tarun** [comment]
@pranav1698 
What is the need of the logo here? How it will be beneficial to the user?

**Comment by pranav1698** [comment]
Hey @meets2tarun,
I made this pr in respnse to issue #107
What i understood was that the logo will be the image of the default logo for the iso like the default wallpaper
If I misunderstood please clear??

**Comment by meets2tarun** [comment]
ok @pranav1698 
Please clear the conflicts and work on the portion that Harsh has mentioned in the top comment.

**Comment by pranav1698** [comment]
Ok @meets2tarun,
On it

**Comment by pranav1698** [comment]
Sorry for the extra commits 
I was trying to squash my commits and something unexpected happen 
I have squashed before but never recieved such results

**Comment by sarnava1** [comment]
@pranav1698 I feel you brother. Same happens with me. Squashing sometimes produces terrible results!!

**Comment by pranav1698** [comment]
I am opening a  new pr beacause of lots of complexities

**Pull request closed without merging**
