### PR TITLE
Solved #307

### LINKED ISSUE #307: redirecting to same page
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

screenshot from 2018-10-23 20-08-13
on clicking on meilix-generator, it is again redirecting to the same page

**Expected Behaviour**

There should not be any link on it because it is already on that page. There is no need of the link.

**Would you like to work on the issue?** YES

### PR DESCRIPTION
**Pull request by Stealthinator16**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This removes the unwanted link which redirects to the same page.

#### Changes proposed in this pull request:

-Removed link which redirects to the same page.

Fixes #307

### CODE REVIEW

**Comment by tabesin** [comment]
Note that your description template of the pull request is incomplete.

**Comment by pranav1698** [comment]
Have you tested your work before opening a PR; @Stealthinator16

**Comment by sarnava1** [comment]
@Stealthinator16 from next time please post screenshots of your work while opening a PR. @tabesin I think this PR can be merged now although I think the issue was not required since it was more of a feature than a bug. Anyways good work @Stealthinator16 and keep going.

**Comment by Stealthinator16** [comment]
@sarnava1  I thought we had to post a screenshot on making UI change.

**Comment by sarnava1** [comment]
> @sarnava1 I thought we had to post a screenshot on making UI change.

Yes for UI changes post screenshots and for this kind of changes you can post GIFs.

**Pull request merged**
