### PR TITLE
Added post information for feature toggles to add various features to meilix - (Solves- #400)

### LINKED ISSUE #400: The feature toggles do no post any input on form submission
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
Currently we have toggles for various features that are required in the Meilix Custom ISO
But, we are not submitting this inputs with the form submission

**Expected Behaviour**
We should store the selected features in a feature so that we can send this array to the build server as a json array.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by pranav1698**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This adds information for the features toggles, and stores them in a features array
This features array is then send to the build server.

#### Changes proposed in this pull request:

- Adding name, value pair to the feature.
- Storing the name-value pair in a feature array.
-

Fixes #400

### CODE REVIEW

**Comment by tabesin** [comment]
Please use a more simple naming scheme than "Generator_*" that should then match the environment variables in https://github.com/fossasia/meilix/blob/master/build.sh

**Comment by pranav1698** [comment]
Ok @tabesin, I am going with FEATURE_* for a meilix feature,
and PACKAGE_* for a package to be installed in the ISO

**Comment by pranav1698** [comment]
Or we can go with something like `SWITCH_ON_*` and `INSTALL_*`

**Comment by pranav1698** [comment]
@tabesin please review now

**Pull request merged**
