### PR TITLE
Generator UI reformation

### PR DESCRIPTION
**Pull request by meets2tarun**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request. #121 
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This PR reforms UI of Meilix Generator and make it look like other FOSSASIA projects.

This PR is an initiation for UI change and several more changes needs to be done.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi Tarun,

you are adding static files to the template directory.
As I understand, in this directory, we should only find files which do not have static content.
Would you like to move it to the static folder?

Please have a look here on how to include static content:
https://github.com/fossasia/meilix-generator/blob/master/templates/index.html#L12

**Comment by meets2tarun** [comment]
Hi @niccokunzmann,
I included all the files in the template folder as I didn't use static in index.html.
Static folder is earlier used as it is required according to the code but now since the code has been changed, the old static folder has no use..

Thanks

**Comment by niccokunzmann** [comment]
I do not know how a client can access the js files through flask. 
Are there environment variables for this? Could you help me understand?

**Comment by niccokunzmann** [comment]
https://meilix-generator.herokuapp.com/ is this the deploy link?

**Comment by niccokunzmann** [comment]
Now, there is only one file changed.

**Comment by meets2tarun** [comment]
@niccokunzmann, I made few mistakes in branch but now I corrected everything
deployed link: https://meilix-test.herokuapp.com

**Comment by niccokunzmann** [comment]
Can this be merged? There is this tag.

**Comment by meets2tarun** [comment]
Yes, this can be merged!
Thanks

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
