### PR TITLE
Empty yield fix 

### PR DESCRIPTION
**Pull request by xeon-zolt**
this is to fix when user directly opens /yield he will be redirected to /index
and this will also fix the problem when empty tags are passed 
#28

### CODE REVIEW

**Comment by meets2tarun** [comment]
@xeon-zolt Please provide a test link to your PR.

**Comment by xeon-zolt** [comment]
https://meilix-generator-test.herokuapp.com/
test url --> https://meilix-generator-test.herokuapp.com/yield it will redirect back to above link

**Comment by meets2tarun** [comment]
Great, the only issue persist is that the page keeps itself in loading state after triggering.

**Comment by meets2tarun** [comment]
@xeon-zolt 
> this will also fix the problem when empty tags are passed

https://github.com/fossasia/meilix-generator/issues/51
Issue still persists.

**Pull request merged**
