### PR TITLE
Enabling Bootstrap tooltip to input boxes

### LINKED ISSUE #344: Enabling Bootstrap tooltip to input boxes
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meili

Would you like to work on this issue?
**Yes**

### PR DESCRIPTION
**Pull request by w3x10e8**
#### Short description of what this resolves:
Enables bootstrap tooltip on input boxes.

#### Changes proposed in this pull request:
Edited index.html 

Fixes #344

### CODE REVIEW

**Comment by w3x10e8** [comment]
@sarnava1 Hey sorry for late reply here is the screenshot 

untitled

@pranav1698 I don't need to make the functionality for data-toggle because it already exists on the page but was not done to all the inputs.

**Comment by pranav1698** [comment]
Ah sorry mate, I was checking the js code in the js files and forgot about the footer files @w3x10e8 
I can see that  the tooltip functionality is added in the footer files

**Comment by tabesin** [comment]
Thank you. Good work.

**Comment by sarnava1** [comment]
Keep up the good work.

**Pull request merged**
