### PR TITLE
This will make the last item in menu to come inside the box on hovering - fix issue #329

### LINKED ISSUE #329: On hovering the last element is not completely inside the box
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
On hover, the last element is not completely inside the box

**Expected Behaviour**
foss

The element should be contained inside the box.

**Steps to reproduce it**

1.  Open the site
2. Click on Menu option
3. Hover on the last element

**Other information:**

**System information:**

```
Your operating system
Windows
```

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Haider8**
#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] There is a corresponding issue for this pull request.
- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
On hovering, the last menu item was not getting into the box. In this pull request i have fixed this issue.
I am providing the screenshot : https://drive.google.com/file/d/1ei79ewz4yAUXq87roF-dxLoMOudwBd0e/view?usp=sharing

#### Changes proposed in this pull request:

-  I have made one major change in "style.css" file(/meilix-generator/static/css/) in line-150, by changing  height to 56px.

Fixes #329

### CODE REVIEW

**Comment by Ryan10145** [comment]
@Haider8 Remove all of the .idea/***.xml files from the project. They aren't relevant to the change and shouldn't be included in the commit.

**Comment by Haider8** [comment]
@Ryan10145 Okay. I have deleted the .xml files from.idea.
Should i delete 'meilix-generator.iml' also?

**Comment by Haider8** [comment]
@Ryan10145 Okay. I have deleted the .xml files from .idea.
Is there a need to delete 'meilix-generator.iml' also? I have made no changes in it.

**Comment by Ryan10145** [comment]
@Haider8 You should remove it from the commit as it appears to be a generated project file from PyCharm and it's not relevant to the change.

Also read [here](https://davidwalsh.name/squash-commits-git) for more info about squashing commits so that you can squash your commits in this pull request.

**Comment by Haider8** [comment]
@Ryan10145 Okay, i have deleted that and thanks for helping me out with squashing.

**Comment by rpotter12** [comment]
@Haider8 paste your heroku deployment link.

**Pull request merged**
