### PR TITLE
Added favicon

### LINKED ISSUE #128: Meilix Generator favicon missing
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

The webapp loads the favicon but unable to find the file so it gives the following error.
screen shot 2018-05-23 at 23 03 50

### PR DESCRIPTION
**Pull request by meets2tarun**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

Fixes #128

### CODE REVIEW

**Comment by meets2tarun** [comment]
Please check this one
@xeon-zolt 

Thanks

**Comment by xeon-zolt** [comment]
@meets2tarun screenshot of the tab with favicon !!

**Comment by meets2tarun** [comment]
@xeon-zolt 
screen shot 2018-05-27 at 22 11 31

Thanks

**Comment by xeon-zolt** [comment]
I am merging this cause I don't want time to be spent on the frontend. we should focus on the functionality  of the generator
plus it does not look very good to me.

**Comment by tabesin** [comment]
It is fine that you merged it, Harsh, but please Tarun use the new logo designs also for the favicon.

**Pull request merged**
