### PR TITLE
Updated the dropdown menu

### LINKED ISSUE #386: Update the dropdown with new projects
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The dropdown needs to be updated with the latest projects

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Dishebh**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Updated the dropdown menu with the latest projects in sequence wth the projects mentioned on the website - https://labs.fossasia.org/ 

Fixes #386

### CODE REVIEW

**Comment by rpotter12** [comment]
@Dishebh Please put your deploy link

**Comment by Dishebh** [comment]
@rpotter12 so I have to deploy it using heroku and share the link, right?

**Comment by Dishebh** [comment]
Or if not, can you please guide me where can I find the link?

**Comment by rpotter12** [comment]
> @rpotter12 so I have to deploy it using heroku and share the link, right?

yes, you have to deploy on heroku and share your deploy link

**Comment by Dishebh** [comment]
x-special/nautilus-clipboard
copy
file:///home/dishebh/Pictures/Screenshot%20from%202019-10-28%2008-45-39.png

Don't know why but whenever I try deploying it on heroku, I get the same website with no changes committed to it. So, here's the screenshot of the changes made.

**Comment by Dishebh** [comment]
Screenshot from 2019-10-28 08-45-39

Don't know why but whenever I try deploying it on heroku, I get the same website with no changes committed to it. So, here's the screenshot of the changes made.




Don't know why but whenever I try deploying it on heroku, I get the same website with no changes committed to it. So, here's the screenshot of the changes made.

**Comment by Dishebh** [comment]
Screenshot from 2019-10-28 08-45-39

Don't know why but whenever I try deploying it on heroku, I get the same website with no changes committed to it. So, here's the screenshot of the changes made.

**Review by rpotter12 — APPROVED** [review]

**Pull request merged**
