### PR TITLE
improvement in #180

### LINKED ISSUE #166: [HTML/CSS/JS] Unified info boxes
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

Currently, we do not have info boxes on the page.

**Expected Behaviour**

I would like to have a link saying `more information` below these entries:

- email
- distro name
- home page
- search engine
- wallpaper

and above tweaks

Clicking this link
- toggles an information text at the same place. This is usable from phones which do not allow hover.
- changes the text to "less information" and "more information" depending on whether it shows the info text.

### PR DESCRIPTION
**Pull request by rpotter12**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

- added image of the question sign.
- added image in the index.html.
- created a function for an alert box.

Fixes #166

screenshot 49

### CODE REVIEW

**Comment by meets2tarun** [comment]
@rpotter12 
Can we shift that question mark on the right side, so it would be easier for one to view.

**Comment by meets2tarun** [comment]
@rpotter12 
Would you like to resolve the conflicts, if you need help in particular, please ask.

Thanks

**Comment by rpotter12** [comment]
@meets2tarun I have no permissions to resolve conflicts and to change any other PR's code in the main repository. I can only change codes of my PR. I can only see the conflicting codes, I can not save them. So I am not able to resolve conflicts.

**Comment by rpotter12** [comment]
@meets2tarun I have updated my code like this.
screenshot 50
Is this looking better than the previous one.

**Comment by meets2tarun** [comment]
@rpotter12 
You can also resolve conflicts by updating the branch with upstream. 
Btw I resolved it this time.

**Comment by meets2tarun** [comment]
Please make a deployment on Heroku and then paste the link, so it would be much easier to review.
https://github.com/fossasia/meilix-generator/blob/master/docs/installation/heroku.md

Thanks

**Comment by rpotter12** [comment]
@meets2tarun review this [https://rpotter.herokuapp.com/](url)

**Comment by meets2tarun** [comment]
Its good.
I think it would be even more great if the message just appears while hovering the cursor over the `question mark` rather than clicking on it.

What do you think?

**Comment by rpotter12** [comment]
I think both the ways are good. 

Tell me if I have to go with your suggestion.

**Comment by meets2tarun** [comment]
Yes, I think to hover is a better option, make the required changes and ask to others too @fossasia/linux-admin

**Pull request merged**
