### PR TITLE
fixing issue #171 and #167

### LINKED ISSUE #171: link description on simple text
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

We can a bug in the dropdown part that we are getting a link description on the text "More on". Only "labs.fossasia.org" is link.
screenshot from 2018-06-22 11-36-45

### PR DESCRIPTION
**Pull request by rpotter12**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Fixes #171 and #167

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@meets2tarun Could you check that I did the merge in a correct way?

**Comment by niccokunzmann** [comment]
@rpotter12 Would you like to spend some more time on the project and also review pull requests? This might be a way for you to contribute to the project, connect to other developers and improve your web development skills.

**Comment by rpotter12** [comment]
@niccokunzmann Yes I would like to spend some more time on the project and also review pull request.

**Comment by rpotter12** [comment]
@niccokunzmann I think you have merged in my forked repository, not in the main fossasia repository.

**Comment by meets2tarun** [comment]
Thanks @rpotter12 ,
Would you please put a screenshot of the webapp, so it would be easier for us to see the outcome.

Thanks

**Comment by rpotter12** [comment]
here is the screenshot of the changes
screenshot from 2018-06-23 09-09-05

**Comment by meets2tarun** [comment]
@rpotter12
you can see here https://github.com/fossasia/meilix-generator/pull/172#issuecomment-399627922 that the email part is broken and the there is no space between on and labs.fossasia.org

**Comment by rpotter12** [comment]
@niccokunzmann @meets2tarun please put `%nbsp;` after **More on**

**Comment by rpotter12** [comment]
created space after More on
screenshot 34

**Comment by meets2tarun** [comment]
There is still the email part is misplaced from its regular format.

**Comment by niccokunzmann** [comment]
The e-mail part is misplaced in the deployed application, too. This is a different issue. Thanks for addressing the two other issues!

**Pull request merged**
