### PR TITLE
fixes #273 (Making the aspect ratio correct in FOSSASIA projects in the nav bar)

### LINKED ISSUE #273: Make the aspect ratio correct in FOSSASIA projects in the nav bar
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The aspect ratio is not okay in the FOSSASIA projects part present in the navbar

**Expected Behaviour**
The width of the images are fine but the height of the images are too small

**Would you like to work on the issue?**
YES

### PR DESCRIPTION
**Pull request by sarnava1**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
As @meets2tarun pointed out in the gitter channel the aspect ratio in the FOSSASIA projects part of the navbar was not nice. 
aspectratioprb

#### Changes proposed in this pull request:

-This PR handles the issue of the aspect ratio. The aspect ratio has been made approximately the golden aspect ratio with height 40px and width 60 px
-The image for the SUSI project was getting pixelated when the height was increased. So a new clear image of SUSI has been introduced in the place of the old image

noprbinaspratio

Fixes #273

### CODE REVIEW

**Comment by sarnava1** [comment]
@meets2tarun and @tabesin please review this.

**Comment by tabesin** [comment]
P.S. As @meets2tarun raised the issue I would like him to decide if and when to approve this PR. Personally I am mostly fine with it but wonder if t he 90px value brings inconsistency across projects.

**Comment by tabesin** [comment]
I meant across Fossasia apps that implement the same

**Comment by meets2tarun** [comment]
@sarnava1 Once check it across different FOSSASSIA projects.

Thanks

**Comment by sarnava1** [comment]
@meets2tarun sure!

**Comment by sarnava1** [comment]
@meets2tarun It is fine.

**Comment by sarnava1** [comment]
@xeon-zolt can you please merge.

**Comment by sarnava1** [comment]
@xeon-zolt @tabesin @meets2tarun Please merge my PR.

**Pull request merged**
