### PR TITLE
fetching the releases

### LINKED ISSUE #59: Use of Github API
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**

Now we are predicting the URL and giving it the users and also facing the intermediate problem of the inactivation of URL in between the building period.

**Expected Behaviour**

We can instead use Github API to fetch the information out of it. These API's are very helpful if we get the best use of it.

https://api.github.com/repos/fossasia/meilix (this contain all the information about the repository and the way to extract them)

https://api.github.com/repos/fossasia/meilix/releases (this contain all the information about the release made by the repository till yet)

https://api.github.com/repos/meets2tarun/meilix/releases/tags/event (this contain the information about the particular tag of the release made by the repository)

The idea is to extract the information from the last URL.
Since we provide the event name (tag), so we know the API URL, now using that URL we can show the user the download link of iso. This also solves the issues of engaging user during the intermediate time of the building.

Your Views??

### PR DESCRIPTION
**Pull request by meets2tarun**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Use of Github API to view release

#### Changes proposed in this pull request:

-This PR will fetch the releases of meilix on the webapp and ask user if they are interested to download any older build.

Fixes #59

### CODE REVIEW

**Comment by xeon-zolt** [comment]
https://meilix-generator-pr-74.herokuapp.com/
the app generated by your pr have a travis_tag error which means env variables are not set up 
so the app.json requires a fix for that

**Comment by xeon-zolt** [comment]
screenshot from 2017-07-16 19-59-26
new error variables are now available after json update

**Comment by tabesin** [comment]
any news on this?

**Comment by meets2tarun** [comment]
closing this for now.

**Pull request closed without merging**
