### PR TITLE
Show info on scroll over: fixes issue #207

### LINKED ISSUE #207: Don't show system messages for (?) info. Instead show info on scroll over
There should not be system pop up messages from a website. Instead implement info in browser on scroll over.

screenshot from 2018-08-02 12-48-02

### PR DESCRIPTION
**Pull request by pranav1698**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This solves the issue of showing system information from dialogs as suggested by @mariobehling , and hence solves issue#207

#### Changes proposed in this pull request:

- In some UI I could not apply the scroll event as it is was not executing 
- I need suggestions for the style

Fixes #207 
I will upload the gif with the changes soon

### CODE REVIEW

**Comment by pranav1698** [comment]
meikix-work-21sept -1

**Comment by pranav1698** [comment]
Sure,  I will work on it soon,

**Comment by pranav1698** [comment]
Hey @tabesin, could you please brief me more about the thing with commas, I couldn't get what you need with the commas about the uniform spacing between them???
P.S. A more clear gif is:
meikix-work-21sept -1

**Comment by tabesin** [comment]
#scroll-to.active , #scroll1.active  , #scroll2.active

**Pull request merged**
