### PR TITLE
[WIP] Implement a new User Interface with better UX.

### LINKED ISSUE #371: Implement new style following market leaders
Most issues in the generator are related to smaller design improvements. There is no target of what design should be achieved and reviewing small issues and PRs takes up time of developers. Rather than implementing a new design please follow the design of market leaders on the web. Please take inspiration from Google and follow their approach. Use similar fonts, icons and headings of the material design. Please implement the following:
* [ ] Design top bar in white as Google.com
* [ ] Design drop-down menu in the same way as Google.com and avoid scroll bars. Also ensure all icons are scaled correctly.
* [ ] Implement form elements similar go Google forms and display helper text right away. Avoid scroll over messages. Keep it simple.
* [ ] Show the version info on the bottom page just like http://opev-webgen-dev.herokuapp.com/

### PR DESCRIPTION
**Pull request by niteshkumarniranjan**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

[https://meilix-generator-ui.herokuapp.com/](https://meilix-generator-ui.herokuapp.com/)

Fixes #371

New UI

### CODE REVIEW

**Comment by sarnava1** [comment]
@niteshkumarniranjan can you give a preview link?

**Comment by niteshkumarniranjan** [comment]
@sarnava1 I have just started working on it. there is no preview link?

**Comment by sarnava1** [comment]
Ohh @niteshkumarniranjan. No problem.

**Comment by niteshkumarniranjan** [comment]
@pranav1698 As most of the browser supports ES6 So I used it but I will convert it back to ES5 no big deal.

**Comment by niteshkumarniranjan** [comment]
@sarnava1 I will reduce the spacing.

**Comment by sarnava1** [comment]
@pranav1698 I think there are some issue with responsiveness when the menu dropdown is there. Please see that once.

**Comment by sarnava1** [comment]
@pranav1698 Yes I saw that :+1:

**Comment by niteshkumarniranjan** [comment]
@sarnava1 @pranav1698  I'm fixing it. I forgot to check the dropdown in mobile.

**Comment by niteshkumarniranjan** [comment]
@pranav1698 the old logo doesn't looks good so designed a logo and put that here basically the meilix logo is for the OS which is present in the and this website is a generator. But if you want me to put that logo then I will put that here.

**Comment by pranav1698** [comment]
The logo should be there;
@niteshkumarniranjan feel free to attach your version of logo

**Comment by meets2tarun** [comment]
Great Work so Far @niteshkumarniranjan

**Comment by niteshkumarniranjan** [comment]
@pranav1698 There is no electricity for more than 20hrs so I am unable to do anything.

**Comment by pranav1698** [comment]
20 hours!!

**Comment by pranav1698** [comment]
No problem! Take your time @niteshkumarniranjan

**Comment by niteshkumarniranjan** [comment]
@rpotter12 Actually, my pc is dead so I can't do anything until I buy a new one.

**Pull request merged**
