### PR TITLE
This removes the unnecessary variable INSTALL which has the same value as the recipe variable - (Solves- #437)

### LINKED ISSUE #437: Unexpected error on clicking the build button
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

**Actual Behaviour**
The current build of the webapp on clicking the build button gives the following error:
`Sorry, unexpected error: str expected, not list`

**Steps to reproduce it**
 - Fill up the form and click the build button
 - The webapp gives the following error:
  `Sorry, unexpected error: str expected, not list`

**System information:**

```
Ubuntu 18.04
```

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by pranav1698**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
This solves the unexpected error `Sorry, unexpected error: str expected, not list`, 
The INSTALL array was not required, the value of the array is same as the recipe array but with different names, I have made the changes equivalent to what we were doing previously 
Check one of the meilix builds triggered by the webapp and  notice that the recipe array is already sending the 3rd party softwares into the build server  

#### Changes proposed in this pull request:

- Removing the INSTALL variable
-
-

Fixes #437

### CODE REVIEW

**Comment by pranav1698** [comment]
@tabesin @xeon-zolt do we need chrome even after we are already adding chromium

**Comment by pranav1698** [comment]
@tabesin we can have the name of the inputs for the softwares same or different, value of the inputs will remain same 
I thought that it will bring clarity if we specify the name of inputs with the value of inputs as we were doing before #435 is merged, we can make the name of the inputs same

**Comment by xeon-zolt** [comment]
chromium and chrome are the same things

**Comment by rpotter12** [comment]
Through meilix-generator we are providing an option for users to choose his/her own browser, so providing an option for chrome also should not be a problem.

**Comment by rpotter12** [comment]
@tabesin this pull request should not be merged because the changes are already made in meilix repository with respect to old changes #435 . This pull request will break the installation of 3rd party software which are selected by checkbox.

**Comment by rpotter12** [comment]
@tabesin @xeon-zolt @meets2tarun please review it again

**Comment by meets2tarun** [comment]
ok, lets have a look,

thanks for the notification @rpotter12

**Pull request merged**
