### PR TITLE
Delete travis_script_1.sh

### LINKED ISSUE #100: Clean-up the repository
We require to finish up all the tests and clean up the test files in the repository
https://github.com/fossasia/meilix-generator/blob/master/travis_script_1.sh

### PR DESCRIPTION
**Pull request by meets2tarun**
Fixes #100

### CODE REVIEW

**Comment by mariobehling** [comment]
@meets2tarun Please follow best practices and do not open PRs in the repo itself. Make PRs from your own branches in your account, please.

**Comment by meets2tarun** [comment]
@mariobehling 
Sorry, I mistakingly did that, and I'll take care of this.

**Comment by xeon-zolt** [comment]
this need to be reverted as it breaks the functionality of the webapp

**Comment by meets2tarun** [comment]
@xeon-zolt How this file is responsible for functionality purpose?

**Comment by xeon-zolt** [comment]
this file is included in the information sent to Travis and will be required in future to send scripts and information in a single script

**Pull request merged**
