### PR TITLE
Update travis_tokens

### PR DESCRIPTION
**Pull request by meets2tarun**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] There is a corresponding issue for this pull request.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] The unit tests pass locally with my changes (provide a screenshot or link for test) 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Needed changes for generating ISO.

### CODE REVIEW

**Comment by meets2tarun** [comment]
Would you please point out the particular code which will break the generator?

And I want to change this because generator is not fully developed and https://travis-ci.org/fossasia/meilix/jobs/354697759#L465 and if generator should be there, then please help to generate an ISO.

**Comment by xeon-zolt** [comment]
read the error its due to no iso present which means build1.sh in meilix/generator needs to be fixed and a check is also required if ISO is not downloaded or partially downloaded 
meilix generator sends the config to Travis which can be used by generator branch but not by master branch master branch is for the generation of the ISO and generator branch is used for scripts used to modify the latest Meilix ISO and send notification to the user with the information of the release

**Comment by meets2tarun** [comment]
Since we are not working with generator branch any more therefore we need to merge this PR and then resolve the error to get the ISO release then the email.

**Comment by meets2tarun** [comment]
@niccokunzmann @tabesin 
Please review this:
Since we are dropping the idea of generator, so we need to shift the triggering to master branch.
After the merge, the code may break then we need to fix that.

Thanks

**Comment by mariobehling** [comment]
> Since we are dropping the idea of generator,

We are not dropping the idea of the generator. I assume you mean we get rid of the generator branch. This is correct, but please pay attention to detail in order not to confuse others and ensure quality of the project.

**Comment by tabesin** [comment]
This cannot be merged now as xeon-xolt pointed out. Furthermore the Meilix master branch needs to be fixed first, then the generator branch migrated. I also don't know if that's the way to proceed.

Side note: "Maybe" we just need to copy the generator branch code over to the master branch and still use generator branch for launching the master branch build for meilix-generator via travis, meaning no ISO customization there anymore but in master.

**Comment by tabesin** [comment]
IOW Generator branch becomes just a travis building proxy for the master branch.

For the master branch we need two cases
1) building locally/travis with default/fallback receipe
2) building travis with receipe fetched from and triggered by webapp generator.
As of the sending mail part this could also be done via master branch case 1.

**Comment by meets2tarun** [comment]
@tabesin 

> the Meilix master branch needs to be fixed first

It is fixed, we yesterday saw a release https://github.com/fossasia/meilix/releases/tag/untagged-ca89ee0bb180bc6f6e19 and the revert commit has made that fix https://github.com/fossasia/meilix/commits/untagged-ca89ee0bb180bc6f6e19 .

>  we just need to copy the generator branch code over to the master branch 

Generator branch only contains importantly https://github.com/fossasia/meilix/blob/generator/build1.sh (way to unzip, customise and repack the iso) and the mailing script (this is already be transferred to the master branch https://github.com/fossasia/meilix/pull/253)

> generator branch for launching the master branch build for meilix-generator via travis,

This is not the purpose of generator branch.

My Experiment:

I although tried the things with https://github.com/meets2tarun/meilix-generator/blob/test/travis_tokens and my meilix master branch is even with fossasia:master.

Build are triggering through the webapp (https://meilix-test.herokuapp.com) with the test branch deployed on Heroku.

**Comment by tabesin** [comment]
No it wasn't 
https://travis-ci.org/fossasia/meilix
https://travis-ci.org/fossasia/meilix-generator

Both fail to build. I restarted the last working meilix build 605 but it then also failed.

**Comment by meets2tarun** [comment]
Meilix is failing due to Travis Credential Issue since due to last PR, my API key get merged.
It can easily be rectified by committing the last API key.

Meilix Generator error needs to be seen. I don't know why that is happening but it also indicates bad credential.  https://travis-ci.org/fossasia/meilix-generator/jobs/379604557#L501

**Pull request merged**
